mucsci-students/2020fa-420-CovidSurvivors

code/UMLClass.py, code/UMLEditor.py, code/UMLModel.py, code/UMLRelationship.py
This is our initial files for the UML Editor. Many features still need to be implemented, but these serve as our basis to branch off of and simultaneously work on other tasks. 
Please review the code and comment any suggestions that you have or ask questions if you do not understand something like the Python syntax. None of the code in these files are final, they can be changed or expanded upon as needed. 
One approving review means we can merge and start working on the other tasks.
=> Initial setup

code/UMLEditor.py
I tried to clean up the prompt for the user. I also colored the prompt.
=> Colored prompt

code/UMLModel.py
Implementations for listing the attributes of a given class and listing the relationships of all classes
=> List/View Class and Relationships

code/CommandData.py, code/UMLModel.py
- changed list_class to list_attributes 
- added list_classes to list all the classes in the model
- modified list_relationships to optionally list relationships for a given class
- updated the commands data
=> List overhaul

code/UMLEditor.py
Added the 'help' command functionality to the execute() function
=> Update to the execute() function

code/UMLModel.py, code/unit-tests/test_UMLEditor.py, code/unit-tests/test_UMLModel.py
UMLModel.py - Added a feature where the console will print a message when user asks for attributes of a class (list_attributes()) and the class has no attributes. The same changes were made for the list_relationships() function.
Renamed UMLModelTest.py to test_UMLModel.py in order to stick to one test file naming convention.
Updated test_UMLEditor.py with a few fixes and made the file more concise.
=> Updated UMLModel.py and 2 test files

code/CommandData.py, code/UMLEditor.py, code/UMLModel.py
Most of the changes have been made in UMLModel.py and CommandData.py.
**Main changes**
1. Removed attribute implementation.
2. Added field implementation.
=> Console: Field Implementation

code/CLI/CommandData.py, code/models/UMLModel.py
=> function to rename a method

code/unit-tests/CLIEditorTest.py
Changed the Test file to contain the following methods:
- create_field()         
- rename_field()        
- delete_field()         
- list_fields()
- create_method()
- rename_method()
- delete_method()
- list_methods()
- list_class()
Tests for the other files are **in progress**.
=> Updated CLI Editor Test

code/WebApp/main.py, code/WebApp/static/js/myscripts.js, code/WebApp/templates/base.html, code/WebApp/templates/card.html, code/WebApp/templates/dashboard.html, code/data/__WorkingModel__.json
I altered the templates to load data from the current working model 
I also had to change how the classes were set to be draggable because it was hardcoded previously
=> Changed the program to load in data

code/models/UMLModel.py
Changed create_field() and create_method() to check for the field/method objects instead of a string literal.
=> Small Update to the UML model

code/unit-tests/UMLModelTest.py
Updated UMLModelTest.py to contain tests for the methods in the current UMLModel.py file.
=> Updated UML Model Testing

code/WebApp/main.py, code/WebApp/static/js/myscripts.js, code/WebApp/templates/card.html, code/WebApp/templates/createClassModal.html, code/WebApp/templates/editClassModal.html, code/WebApp/templates/modalForm.html
For populating the edit class modal, I used a server request and used Flask to generate the form and a javascript call to insert the form into the page. Which is pretty cool and works nicely. 
I also changed create class to load without any field/method/relationship inputs.
Closes #127
=> Implemented editing a class

code/WebApp/static/js/myscripts.js, code/WebApp/templates/modalForm.html, code/models/UMLModel.py
I fixed a bug where relationships were not sent in POST requests 
I fixed a bug where deleting a class does not delete the relationships to other classes. 
I also changed create_relationship to now check if a relationship exists in either class. (Previously it only checked one class)
Closes #135
=> Fixed some bugs with relationships

code/CLI/CommandData.py, code/models/UMLModel.py
Created move_up_method and move_down_method for the console version of the program.
=> Move method console

code/unit-tests/UMLClassTest.py, code/unit-tests/UMLFieldTest.py, code/unit-tests/UMLMethodTest.py
Added a unit-test file for the Field Class and Method class
- Tested rename() function
Changed UMLClassTest.py to include test for the new implementations from UMLClass.py
=> New Testing features for fields and methods

code/WebApp/main.py, code/WebApp/static/js/myscripts.js, code/WebApp/templates/modalForm.html, code/data/__WorkingModel__.json, code/models/UMLModel.py
=> Added inputs for visibility and types for fields/methods

code/unit-tests/CLIEditorTest.py
Added tests to the CLIEditorTest.py for the following methods:
- move_up_field
- move_down_field
- move_up_method
- move_down_method
=> Added move_up/move_down tests

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Added CONTRIBUTING.md which lists the contributors and ways to contribute.
=> Community standards

code/WebApp/main.py, code/WebApp/templates/dashboard.html, code/command/command.py
I implemented Command and Memento for the GUI
I feel like my implementation is not great because each command needs to load and save the model.
I also feel like error messages should be improved for this, which I can work on for another task. 
Closes #186 
Closes #161 
Closes #162
=> Implemented Command and Memento for GUI

code/models/RelationshipType.py, code/models/UMLModel.py
Created arrow representations for relationships and added backwards arrows for inverse relationships.
=> Added Arrow Representation for Relationships

code/CLI/CLIEditor.py, code/CLI/CommandData.py
- Commands in CommandData.py have been reordered.
- The 'help' command now outputs the commands in that order and groups them into categories.
=> Changed ordering and output of 'help' command

code/CLI/CLIEditor.py, code/WebApp/main.py, code/command/command.py, code/models/UMLModel.py, code/unit-tests/test_UMLModel.py
I implemented error messages and statuses for each UMLModel method so that we can better detect and give errors to the user. 
Closes #156 
Closes #59
=> Error statuses

code/models/UMLField.py, code/models/UMLMethod.py, code/models/UMLParameter.py, code/models/Variable.py
=> Implemented Parameter and the prototype design pattern

code/WebApp/templates/dashboard.html
=> Added icons to Undo/Redo buttons

code/WebApp/main.py, code/WebApp/static/css/style.css, code/WebApp/static/js/myscripts.js, code/WebApp/templates/dashboard.html
I implemented flash error/success messages. 
Closes #141
=> Implemented flash error/success messages

code/CLI/CLIEditor.py
Refactored the REPL Class to avoid repeating code.
=> Refactored CLIEditor.py

code/CLI/CLIEditor.py
Fixed checks for correct number of arguments. Before, the program would crash when an invalid usage was entered for a valid command. 
I also moved the model and command_history into the REPL to clean up messy globals. 
Closes #206
=> Argument Checking

code/models/UMLModel.py, code/unit-tests/test_UMLClass.py, code/unit-tests/test_UMLField.py, code/unit-tests/test_UMLMethod.py, code/unit-tests/test_UMLModel.py, code/unit-tests/test_Variable.py
**Added Model Tests for**:
- UMLCLass.py
- UMLField.py
- UMLMethod.py
- UMLModel.py
- Variable.py
**Things that still that still need to be implemented**:
- Tests for '*get_raw_data()*' and '*from_raw_data()*' functions that exist in most of the models
- More UMLClass.py tests
- More UMLModel.py tests
- Refactor/Rewrite CLIEditorTest.py and add more tests
=> Added New Tests

code/CLI/CLIEditor.py
All field commands now have tab completion.
Closes #228
=> Added Tab Completion for Fields

code/WebApp/main.py, code/WebApp/static/js/myscripts.js, code/WebApp/templates/base.html, code/WebApp/templates/card.html, code/WebApp/templates/dashboard.html, code/models/UMLClass.py, code/server-data/This is cool :D.json
=> Implemented the GUI relationship arrows

code/CLI/CLIEditor.py, code/models/UMLModel.py
- Added Tab completion functionality for parameter and relationship commands.
- Changed The way list_parameters displays the parameters.
- Fixed a bug with delete_relationships where the method took too many arguments.
=> Tab Completion for Params and Relationships

code/WebApp/static/css/style.css, code/WebApp/templates/dashboard.html, code/WebApp/templates/models.html
=> Changed color scheme of select model page

code/unit-tests/test_UMLModel.py
Namely:
list_class
- list_classes
- list_fields
- list_methods
- list_parameters
- list_relationships
- *Note*: Also added set_class_position
=> Added list_x Tests to UMLModel
